#version: '3'

services:
  backend-spring:
    build: '.'
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - sector
  frontend:
    build: 'src/frontend/sector-frontend/'
    volumes:
      - './src/frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - backend-spring
#    РЕСТАРТ ЕСЛИ ОШИБка
#    restart: unless-stopped
    networks:
      - sector
networks:
  sector:
    driver: 'bridge'